### ISSUE TITLE
Problem calling ulimit in worker container 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#104]
When `KTOOLS_MEMORY_LIMIT = True` is set `run_ktools.sh` calls 

```
cmd_mem_limit = 'ulimit -v $(ktgetmem {})'.format(max_process_id)
```

which intermittently fails with:
```
Exception: Error running ktools: run ktools.sh: line 168: ulimit: virtual memory: cannot modify limit: Operation not permitted
```

Note: current behaviour is to check `/sys/fs/cgroup/memory/memory.limit_in_bytes` for maximum memory limit.  Reduce that by 5%  and divide between number of system cores, which becomes the new per process memory limit.

**Comment by mpinkerton-oasis** [comment]
@sambles is this still open?

**Comment by sambles** [comment]
ulimit removed and replaced with `ktools_error_guard`
