### ISSUE TITLE
xref connection between direct insurance and reinsurance fm files

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisPlatform#105]
There may be an inconsistency between output_ids from the direct insurance fm files and level 1 from_agg_ids in the reinsurance fm files.  These ids need to be consistent so that risk level terms are applied correctly in reinsurance.  The attached piwind test dataset highlights the issue.
For discussion.
[piwind fm xref.xlsx](https://github.com/OasisLMF/OasisPlatform/files/3059396/piwind.fm.xref.xlsx)

**Comment by sambles** [comment]
fix after: https://github.com/OasisLMF/OasisLMF/tree/1.3.8
