### ISSUE TITLE
Logging - V2 input generation and losses tar should include log files for all sub-tasks 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#1075]
## Issue Description
For V1 analyses, the log files are included in the result tar files.  

Do the same for V2 tar files, download all sub-task logs and put them into a `log/<uuid>.txt` dir.

**Comment by sambles** [comment]
**Note:**  `run_log_file` also needs aligning between `v1` and `v2`

> **carlfischerjba:** v1 and v2 analysis run logs are accessible via the API but for a v2 analysis the tar.gz contains a logs subdirectory instead of containing everything at the root of the archive as is the case for v1. Makes it a bit harder to do like for like comparisons or parametrise tests to run on both versions of a model.

**Comment by carlfischerjba** [comment]
The `<uuid>.txt` file containing the combined input gen logs seems to have disappeared for V1 analyses too. We've seen this on NRMC which is currently using Oasis 2.3.5 and the worker is using Oasis 2.3.6.
