### ISSUE TITLE
Update cookie cutter template for new API and complex models

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisPlatform#194]
Proposed structure:

.
├── apt.txt
├── bin
├── docker
│   └── Dockerfile.[SUPPLIER]_[MODEL]_worker
├── data_version.json
├── docs
├── jenkins
│   └── [SUPPIER]_[MODEL].groovy
├── meta-data
├── model_resources.json
├── oasislmf.json
├── requirements.txt
└── src
└── tests

The required files and folders are:
apt.txt: contains a list of apt package dependencies.
bin: directory containing any pre-compiled model binaries.
data_version.json: contains the supported combinations of model data and keys data supported by the code.
docker: directory containing model dockerfiles.
docs: directory containing any model specific documentation.
jenkins: directory model specific build pipeline scripts.
meta-data: directory containing any model meta-data such as hazard maps, event catalogues etc.
model_resources.json: configuration file for model integration with the Oasis platform.
oasislmf.json: configuration file for model execution via the Oasis MDK.
requirements.txt: contains a list of any Python package dependencies.
src: directory containing any model source code file.
tests: all test data and expected results.

**Comment by mpinkerton-oasis** [comment]
@sr-murthy @sambles can you review the above. This has come out of the recent complex model discussions. Is there additional structure that should be included for standard models?

**Comment by sr-murthy** [comment]
@mpinkerton-oasis I can see no additional changes required to support standard models in relation to the MDK.

The only requirement that the MDK has for a model repository structure is in relation to how the model lookup source code is structured - it needs to be able to load the keys lookup for a given model. For non-complex custom models, as long as the model lookup is in a Python subpackage, and the lookup class is prefixed with the model ID correctly (`<model ID>KeysLookup`) and extends `OasisBaseKeysLookup` (from `oasislmf.model_preparation.lookup`) and implements `process_locations` appropriately, there shouldn't be any problem.
