### ISSUE TITLE
Attempt to run generate inputs with data files fails

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisPlatform#227]
Currently (v1.2.0), `src.server.oasisapi.analyses.models.create_complex_model_data_file_dicts` references some non-existent attributes of the `DataFile` model; `cmdf.data_file` should be `cmdf.file`, and `cmdf.file_name` should be `cmdf.filename`.

Simply changing those doesn't quite fox the problem, though; for some reason, `cmdf.filename` returns a blank string, and hence the model execution worker is unable to further process the file. I don't fully understand this (perhaps my unfamiliarity with Django!), as the data is populated when I query it via the Swagger UI .

**Comment by DanielFEvans** [comment]
I think the issue with `DataFile.filename` being blank is that the `update_filename()` function isn't being called. I can access `DataFile.file.filename`, which returns the original, uploaded filename.

I'm not sure if there's any particular reason to have `DataFile.filename` as a separate field, if it only ever mimics `DataFile.file.filename`.

**Comment by sambles** [comment]
#229
