### ISSUE TITLE
API - Fix Responses types

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#234]
The documented response models are incorrect for the following:

*/access_token/*   `TokenObtainPair`
*/refresh_token/* `TokenRefresh`

*/oed_peril_codes/*

**Comment by sambles** [comment]
https://github.com/axnsan12/drf-yasg/issues/407

**Comment by johnthagen** [comment]
See also: https://github.com/davesque/django-rest-framework-simplejwt/pull/145

**Comment by sambles** [comment]
https://drf-yasg.readthedocs.io/en/stable/custom_spec.html
https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#module-drf_yasg.openapi

**Comment by sambles** [comment]
> See also: [davesque/django-rest-framework-simplejwt#145](https://github.com/davesque/django-rest-framework-simplejwt/pull/145)

Thanks!
