### ISSUE TITLE
API - v1_portfolios_create, v1_portfolios_list - Swagger response definition not matching data returned

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/OasisPlatform#238]
**Swagger definition**

Portfolio {
id,
name,
created,
modified
}

**Actual response**

{
    "accounts_file": null,
    "created": "19-08-29T12:03:46.256875+0000",
    "id": 1,
    "location_file": null,
    "modified": "19-08-29T12:03:46.263352+0000",
    "name": "foo",
    "reinsurance_info_file": null,
    "reinsurance_scope_file": null
}

**Comment by sambles** [comment]
fixed in #242
