### ISSUE TITLE
API - v1_analyses_create, v1_analyses_list - Swagger response definition not matching data returned

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/OasisPlatform#239]
** Swagger **
Analyses {
created,
modified,
name,
id,
portfolio,
model,
status,
complex_model_data_files
}

** Actual **
{
    "complex_model_data_files": [],
    "created": "19-08-29T13:04:21.781861+0000",
    "id": 1,
    "input_file": null,
    "input_generation_traceback_file": null,
    "lookup_errors_file": null,
    "lookup_success_file": null,
    "lookup_validation_file": null,
    "model": 1,
    "modified": "19-08-29T13:04:21.788470+0000",
    "name": "TestAnalysis",
    "output_file": null,
    "portfolio": 1,
    "run_traceback_file": null,
    "settings_file": null,
    "status": "NEW",
    "summary_levels_file": null
}

**Comment by sambles** [comment]
Fix in #242
