### ISSUE TITLE
KTOOLS - Lock File not working

### ISSUE THREAD

**Issue by lucaspanayiotou** [OasisLMF/OasisPlatform#24]
The ktools lock file does not seem to be working properly. I am not sure it is being created or correctly locking out the our Calc servers

We are using working version 0.394.0

**Comment by mpinkerton-oasis** [comment]
Confirmed that this is working is the location on the lock file is shared between all the workers, and the lock file path is the same. This can also be confirmed using the ```lslocks``` command when an analysis is running.
