### ISSUE TITLE
API - v1_analyses_run - Swagger parameter definition doesn't match implementation and has undefined return value

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/OasisPlatform#240]
The swagger API lists one arguments to the call, where there should be none. Also the response is just defined as an "object"

    "/v1/analyses/{id}/run/": {
      "post": {
        "operationId": "v1_analyses_run",
        "description": "Runs all the analysis. The analysis must have one of the following\nstatuses, `NEW`, `RUN_COMPLETED`, `RUN_CANCELLED` or\n`RUN_ERROR`",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {}
            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {}
            }
          }
        },
        "tags": [
          "v1"
        ]
      },

**Comment by sambles** [comment]
fixed in #242
