### ISSUE TITLE
KTOOLS - Batch Count not working

### ISSUE THREAD

**Issue by lucaspanayiotou** [OasisLMF/OasisPlatform#25]
KTOOLS_BATCH_COUNT yml variable does not seem to be correctly restricting the amount of cores that are available for a run.

using worker version 0.394.0

**Comment by mpinkerton-oasis** [comment]
Using `OASIS_API_KTOOLS_BATCH_COUNT` as the environment variable in the compose yml drives the number of processes correctly.
