### ISSUE TITLE
Support for Japanese step policies

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisPlatform#27]
Explanation how step policies work and example attached.
HowStepPoliciesWork.png StepPolicyExample.png

So from the example, pays out are:

90k if the ground up loss exceeds 100k
450k if the ground up loss exceeds 20% of the insurable value
900k if the ground up loss exceeds 70% of the insurable value

(ground up loss could be just Building loss or just contents loss (excluding other coverages).
![steppolicyexample](https://user-images.githubusercontent.com/13663877/47076764-69fb3c00-d1f7-11e8-865e-788fea8e6938.png)

**Comment by mpinkerton-oasis** [comment]
Waiting to receive worked examples.

**Comment by mpinkerton-oasis** [comment]
@johcarter any details to add to this yet, or still blocked?

**Comment by johcarter** [comment]
we have a meeting in the diary for 21st march with GC to discuss their worked example
