### ISSUE TITLE
Make the framework log (on warning or error level) when reverting behaviour

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/OasisPlatform#274]
If the MDK framework reverts it's behavior, there needs to be some clear logging that this is taking place. It will cut down the time spent chasing a problmen significantly

**Comment by sambles** [comment]
Add to info log:  
* docker image / tag
* MDK version:
* Ktools version:

Add check for matching: 
`ModelVersion.csv`  vs the environment vars

**Comment by mpinkerton-oasis** [comment]
Clarified requirement with @ndaqjn 
For complex models, custom GUL component is picked up by default if they match he naming convention. This should be made explicit so that an exception is raised if the custom component has not been installed.
