### ISSUE TITLE
Adding 0% / model default / 100% correlation options that can be accessed via a UI

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/OasisPlatform#28]
Users (including GC and JBA) have requested functionality which allows them to run models with 0 and 100% secondary uncertainty correlation via the UI (in addition to the model default correlation), rather than needing different models with different assumptions built in.

NB: We need to think about whether 0 correlation really is zero, or whether we still keep the coverages 100%  correlated (and everything else 0 correlated)

**Comment by mpinkerton-oasis** [comment]
GC issue addressed.
