### ISSUE TITLE
Celery - change task status to running when read from the queue

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#281]
Currently its set on sending a task to the queue:
https://github.com/OasisLMF/OasisPlatform/blob/develop/src/server/oasisapi/analyses/models.py#L146
https://github.com/OasisLMF/OasisPlatform/blob/develop/src/server/oasisapi/analyses/models.py#L203

**Comment by mpinkerton-oasis** [comment]
Could this be due to pre-fetching task. Using "-O fair" would seem sensible for our setup anyway.

https://celery.readthedocs.io/en/latest/userguide/optimizing.html#prefork-pool-prefetch-settings

**Comment by sambles** [comment]
#288 - PR
