### ISSUE TITLE
Support object storage for model data

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/OasisPlatform#284]
Support using S3 (or equivalent object storage) for shared data. This makes a multi-tentant setup a lot easier and cheaper.

**Comment by mpinkerton-oasis** [comment]
In the short term, could look at mounting S3 using S3FS or similar.

**Comment by mpinkerton-oasis** [comment]
What about just copying down the data as a pre-execution step?

**Comment by ndaqjn** [comment]
So what is that S3 stats based on exactly? We have installations where we query serveral TB of data without any significant performance problems, in particular for sequenential reads. 

I don't think copying the file to the container is a good idea. That doesn't get rid of the problem with having huge filesystems inside the container.  

Preferably I would like to see something where there is are several options available and that is has pluggability, for extending the system with additional reading options.

**Comment by mpinkerton-oasis** [comment]
Following on from discussion, agreed first step is to put the analysis data rather the model data onto S3 and use the Python toolkits (Boto?) to read/write data.

**Comment by mpinkerton-oasis** [comment]
Supporting Azure blob storage important requirement as well.

**Comment by sambles** [comment]
Make file-share mode explicit `STORAGE_TYPE=fs-share`
