### ISSUE TITLE
Automate release notes

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#290]
> Pull out sections of an rst document, so if we put in start_latest_release and end_latest_release markers in each of the changelogs we could pull these together into a single latest release summary

**Comment by mpinkerton-oasis** [comment]
I have done this, and started incorporating in git docs.

**Comment by sambles** [comment]
In GitHub?

**Comment by mpinkerton-oasis** [comment]
I did it in the changelogs. The release notes are trickier as there isn't an actual md document in the repo. You can use the hub utility to pull out the md for a particular release, which might be useful for compiling the documentation.
