### ISSUE TITLE
Problem with Swagger file in 1.4.2-rc1

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/OasisPlatform#295]
The endpoint model/id/settings uses the ModelSettings object, but gets overwritten by the object parameter called model_settings.

So when our java code is generated we get a class file ModelSetttings.java but also a property model_settings in AnalysisSettings.

Both are added to the model-package.

**Comment by sambles** [comment]
- [ ] Add Maven build test
- [ ] Update "title" fields (non-matching)
- [ ] Align model_settings in analysis settings with ModelParameters spec
