### ISSUE TITLE
Error  in input generation

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/OasisPlatform#296]
```
[2020-01-22 16:34:54,164: ERROR/ForkPoolWorker-1] Task generate_input[081577a6-245d-403a-908e-a33c060fd708] raised unexpected: OasisException("Calculation Rule mapping error, non-matching keys:\n   ('deductible_gt_0', 'deductible_min_gt_0', 'deductible_max_gt_0', 'limit_gt_0', 'share_gt_0', 'attachment_gt_0', 'ded_type', 'ded_code', 'lim_type', 'lim_code')\n   (1, 1, 0, 0, 0, 0, 2, 0, 0, 0)\n   (1, 0, 1, 0, 0, 0, 2, 0, 0, 0)\n",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/worker/src/model_execution_worker/tasks.py", line 329, in generate_input
    GenerateOasisFilesCmd(argv=run_args).run()
  File "/usr/local/lib/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/worker/src/oasislmf/oasislmf/cli/model.py", line 263, in action
    write_chunksize=write_chunksize
  File "/home/worker/src/oasislmf/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/worker/src/oasislmf/oasislmf/manager.py", line 555, in generate_oasis_files
    fm_aggregation_profile=fm_aggregation_profile
  File "/home/worker/src/oasislmf/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/worker/src/oasislmf/oasislmf/model_preparation/il_inputs.py", line 567, in get_il_input_items
    il_inputs_df['calcrule_id'] = get_calc_rule_ids(il_inputs_df)
  File "/home/worker/src/oasislmf/oasislmf/model_preparation/il_inputs.py", line 90, in get_calc_rule_ids
    raise OasisException(err_msg)
oasislmf.utils.exceptions.OasisException: Calculation Rule mapping error, non-matching keys:
   ('deductible_gt_0', 'deductible_min_gt_0', 'deductible_max_gt_0', 'limit_gt_0', 'share_gt_0', 'attachment_gt_0', 'ded_type', 'ded_code', 'lim_type', 'lim_code')
   (1, 1, 0, 0, 0, 0, 2, 0, 0, 0)
   (1, 0, 1, 0, 0, 0, 2, 0, 0, 0)
```

**Comment by ndaqjn** [comment]
Input files
[portfolio.zip](https://github.com/OasisLMF/OasisPlatform/files/4103435/portfolio.zip)

**Comment by johcarter** [comment]
Ill take a look @ndaqjn

**Comment by johcarter** [comment]
There is no calcrule support for deductible and min deductible only (accounts 66-67) or deductible and max deductible only (accounts 68-69). Probably because we've never received a real policy example like this.
Work around:
Account 66-67
since deductible is % TIV, this can be converted to an amount and then the greater of this value and min deductible can be entered as a minimum deductible only
Account 68-69
since deductible is % TIV, this can be converted to an amount and then the smaller of this value and max deductible can be entered as a maximum deductible only

**Comment by ndaqjn** [comment]
I'll pass the information on to Aiste. Thank you

**Comment by johcarter** [comment]
welcome

**Comment by jones-matt** [comment]
Thanks Joh. Will you put a fix in to stop people needing a work-around? The FM should ideally be able to cope with either a minded + ded or a maxded + ded.

**Comment by johcarter** [comment]
Actually thinking about it @jones-matt , a carried deductible can come into play such that effective + ded > max, even if ded amount < max. So it is a dynamic calculation.

Therefore yes, we should add a new calcrule and convert type 2 deductibles into amounts to be consistent with the treatment of other type 2 deductibles.

Do you have any real policy example of these scenarios?

**Comment by jones-matt** [comment]
I don't I'm afraid - but isn't the logic identical to the more complicated  ded + minded + maxded case (which is covered by your calcrules), but setting either minded = 0 (to test the ded + maxded case) or maxded = inf (to test the ded + minded case) ?

**Comment by johcarter** [comment]
yes, it just helps me to prioritise the work.  cheers Matt.

**Comment by aiste-kalinauskaite** [comment]
@johcarter , in the old version of ModEx, this must have been massaged prior to reaching fmcalc, as these examples (66-69) are coming from the old tests I did. So in terms of prioritisation, from users perspective these cases worked before and they no-longer work once we move to the API version. Could this be prioritised to make into March Release?
In terms of test files, can you use those that Jonas sent? They are based on the real examples I have seen many times in the past.

**Comment by ndaqjn** [comment]
From Aiste:

I have finaly managed to get the files to run!  and I am attaching the files that run successfully (Runs.zip) and the ones that fail (Fails.zip).

We are getting back to the first two hypothesis I had that the OED spec is strictened by either Oasis or CoreLogic (as in my view – both of the atatched sets of files should have run successfully). Questions (as extracted from the differences between the two sets of files):

Acc
1)	Are there any checks on perils?
2)	Are all perils (AA1, QQ1, QEQ, QSL, QFF) implemented as per key facts?

Loc

- Can adding AreaName or any of the Geogscheme/Geogname pairs make the input generation fail?
- Can users leave YearBuilt blank (it’s not a required field by either OED or CoreLogic)?
- Can users leave NumberOfStoreys blank (it’s not a required field by either OED or CoreLogic)?
- Are all perils (AA1, QQ1, QEQ, QSL, QFF) implemented as per key facts?
- Are users required to have any of the below fields populated in order to run CoreLogic’s USEQ model?
- 
1.	PercentComplete
- 2.	StreetAddress
- 3.	City
- 4.	AddressMatch
- 5.	FloorArea
- 6	FloorAreaUnit

[Runs.zip](https://github.com/OasisLMF/OasisPlatform/files/4109575/Runs.zip)
[Fails.zip](https://github.com/OasisLMF/OasisPlatform/files/4109577/Fails.zip)

**Comment by sambles** [comment]
for **Loc**
1)  from the Oasis code base Point of view it shouldn't fail, but might be required in the model's lookup implementation
2) blank should be Ok
3) same as above

**Comment by mpinkerton-oasis** [comment]
This will be addressed by the work in £
