### ISSUE TITLE
Additional validation for model settings:

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#300]
As well as meeting the JSON schema also check that: 

- "name" values are unique across all paramater types, so for example the following is invalid:
```
      "boolean_parameters":[
         {
            "name":"clashing_name",
            "desc":"Boolean option",
            "default":false
         },
       "float_parameters":[
         {
            "name":"clashing_name",
            "desc":"Some float value",
            "default":1.0,
            "max":1.0,
            "min":0.0
         },
```

- The "default" option in `event_set` and `event_occurrence_id` has been defined under the "options" section

**Comment by ndaqjn** [comment]
Also make it clear that the default values should be a value from a collection not the descriptive name

**Comment by sambles** [comment]
yup good call, also:
* both the "name" and "id" fields should also be a limited character set like `[a-zA-Z0-9_-]`

**Comment by ndaqjn** [comment]
Do we need two descriptive type fields? One for a Tooltip-type info and one that is displayed in the UI as the name of the option?

**Comment by sambles** [comment]
The `"name"` option is intended as the key name used when adding the parameter to an analysis settings file: 
```
{ 
    "clashing_name": <some_value>
```
where `"desc"` is a text description for the UI

**Comment by ndaqjn** [comment]
Sure, but there are three that you might want
* name - the name of the parameter in the settings file (return_period)
* desc - What is presented in the ui (Return period)

**Comment by sambles** [comment]
ah ok i see what you mean, yup its probably worth adding the third option more in depth option

**Comment by ndaqjn** [comment]
There are two additional concepts I think we should add. Since all the parameters are organized by type. The model provider needs something to organize them in a logical way. I think we should have two additional settings.

`parameter_groups: [
  {
    "name": "group_1"
    "desc": "This is group one"
    "fields:": ["parameter1", "parameter2"...]
  }

  "parameter_presentation": ["group1", "parameter7", "parameter8", "group9"]
]`

All references to parameters and groups are by the name

**Comment by sambles** [comment]
Possibly add checking for:
https://github.com/OasisLMF/OasisLMF/issues/485

To make sure the data_files are connected to the model.
That would mean all files need to exist before posting the `model_settings.json` which could be annoying to the user

**Comment by sambles** [comment]
* enforce strings only in the `dictionary_parameters` type
