### ISSUE TITLE
Define groups for models

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisPlatform#305]
A model should have a set of OED fields that it uses to define correlation groups when running analyses. This was possible in Flamingo, but it the latest platform groups are based on location ID only.

- [x] Add a group fields list to model settings, taking OED field names.
- [x] Generate the groups using the set group fields in the model settings when building analysis input files.
- [x] Update PiWind to illustrate this functionality.

**Comment by mpinkerton-oasis** [comment]
To check - is there particular logic to apply around the OED correlation group field.

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisPlatform/pull/337
https://github.com/OasisLMF/OasisLMF/pull/527
https://github.com/OasisLMF/OasisPiWind/pull/62
