### ISSUE TITLE
Support for OED DedType and LimitType fields in financial module 

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisPlatform#31]
Until OED DedType and LimitType are supported, all deductible and limit values between 0 and 1 are treated as % TIV. So % Loss deductibles and limits are not supported and will be treated as % TIV if present in OED acc and loc input file

**Comment by mpinkerton-oasis** [comment]
@johcarter what is the status of this?

**Comment by johcarter** [comment]
to do

**Comment by sr-murthy** [comment]
This is also simple to add, and will be part of the changes in FM for the next release. It's pretty simply, updating the default loc. and acc. profiles to add the deductible and limit type, and deductible and limit codes columns at each level, and then updating some steps in FM terms generation to use values from those columns appropriately.

**Comment by johcarter** [comment]
Could you make this the next functionality task, please @sr-murthy ?

**Comment by sr-murthy** [comment]
OK. I did look at doing this for the previous release - but I had some questions. It may be best to discuss next Thursday.

**Comment by sr-murthy** [comment]
OK, I will be in next Tuesday as well.
