### ISSUE TITLE
Using Social-Auth-App-Django for logins to Open Access Models

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OasisPlatform#315]
The idea is to use the Social Auth-app in Django to set up the multiple logins to access the Oasis UI for the Open Access Models.

This allows each login to access the same server through Github where Oasis can control the security for each user. This will restrict each user to view only their own data and model runs.

The link below goes through the installation of the social authentication through PyPi and its config.

https://hashedin.com/blog/a-guide-to-using-social-login-with-django/

**Comment by sambles** [comment]
https://www.keycloak.org/docs/latest/getting_started/index.html

**Comment by sambles** [comment]
Should be possible in the updated platform with the switch to keycloak, but thats something an organization would need to configure:

https://www.keycloak.org/docs/latest/server_admin/#social-identity-providers
