### ISSUE TITLE
Pre-analysis exposure modification

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisPlatform#322]
This feature will add the ability to specify a model specific pre-analysis hook for exposure modification, that allows OED to be processed by some custom code. This could be used for business use cases such as geo-coding, exposure enhancement, or dis-aggregation.

Interface to be implemented:
input OED file location: original OED to read from.
output OED file location: transformed OED to write to.
settings json: any settings required by the modification.

- [ ] Integrated into Celery task framework
- [ ] Integrate into API
- [ ] Integrate into UI
- [ ] Provide example in PiWing

**Comment by DanielFEvans** [comment]
Input/output OED: for our current use case, we would need to take in and return modified versions of both the Loc and the Acc file. It would seem sensible to include the reinsurance files, too, for any other users.

We would require access to our model data directory and model software, implying that our worker image would need to perform the task, and be told where to find the data on the system (in both the lookup and gulcalc, Oasis passes us paths that let us find the data directory).

Our task would potentially be quite long-running, so a status accessible via the API (queued/running/complete/failed) would be needed for a UI.

For the input JSON, the format matching that of the model_settings section of analysis_settings would do. We'd be happy with either JSON that only contains our options, or one that contains them in a subsection (as is the case with analysis_settings).

We'd like to be able to return some data to the user. I currently envision this being a logfile (e.g. where there any portfolio locations we couldn't pre-process, and hence have removed?), as well as the user being able to download the modified portfolio in case they want to see what we've done (I think the Oasis API already supports downloading portfolio data, so this could be quite easy - just serve up the modified version).

**Comment by simkoum** [comment]
Some requirements from my side would be: 
- Being able to import all OED files (including re-insurance) and being ok to change not only any value but also delete/add columns & rows (but consistent with OED format).
- It would maybe make sense that any validation of the OED fields happens after this step.
- Access to the lookup keys_data folder. 
- Pre-analysis parameters via a JSON input is fine.
- Ability to download the resulting OED files + other output ( e.g. reject file, error file, log files etc)
- Ability to output multiple sets of OED files could be useful as well.

**Comment by sambles** [comment]
Note from **Daniel Evans**
> One other thought I've had is that it would be useful to us if the model data directory was passed on to the function. Thinking ahead, if it were behind an API or similar, it'd be quite difficult to build a config file pointing to model data that lives in an unknown location on the server. That might already be planned once you move on to adding this to the API, though.

**Comment by mpinkerton-oasis** [comment]
@sstruzik @sambles can we close? Any of the comments need to be turned into other issues?
