### ISSUE TITLE
Rebranding and updating original 'Simplitium OED'.pdf doc for Oasis documentation

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OasisPlatform#333]
* Waiting for response from Matt Jones (NASDAQ) on any possible ramifications of using original document.
* Email request was sent to Matt on 2nd March 2020.
* May have to reference original document

**Comment by MattDonovan82** [comment]
In progress of splitting up original OED doc into the separate sections in the Oasis OED repo. Will move each section into the appropriate use cases - working with Mark P.

**Comment by mpinkerton-oasis** [comment]
Will track in Open Data Standards repo.
