### ISSUE TITLE
Corrupted tar files

### ISSUE THREAD

**Issue by honlau** [OasisLMF/OasisPlatform#34]
There is an intermittent problem that affects the tarring process created corrupted tar.gz files, examples attached (both run with same input files and run parameters):

example corrupted file 
[dadf1af9b4cb4023a6b75b050add8e80.tar.gz](https://github.com/OasisLMF/OasisPlatform/files/2549503/dadf1af9b4cb4023a6b75b050add8e80.tar.gz) 

example good file
[cc917b292a4344febc5444ae55397a03.tar.gz](https://github.com/OasisLMF/OasisPlatform/files/2549502/cc917b292a4344febc5444ae55397a03.tar.gz)

This is rarely seen when running single analyses, but occurs more frequently when several executions are running resulting in signficant read/write activity on the server.  In this particular case, I had 20 runs in progress and 3 showed a "Failed to extract tarball" error in the ModEx UI.

In windows, using 7zip the files corrupted file extracted with errors, but lost most of its data (only one file was partially extracted).
In linux the command "tar -xzvf dadf1af9b4cb4023a6b75b050add8e80.tar.gz" also partially extracts one file only, with errors.

Can you please implement an integrity check on the tar.gz file so that it deletes and tries again if it fails?
There may an overhead on the task, but to fail on the simple bit (moving data) is quite annoying, especially if it means losing hours worth of model execution data.

**Comment by mpinkerton-oasis** [comment]
@honlau have you seen this with the 397 build?

**Comment by honlau** [comment]
@mpinkerton-oasis I believe I saw this still happening in the 397 release though I can't seem to find the comment where I updated the issue anymore.  Was this actually fixed?
Since the beginning of the year, I have migrated to a better testing setup with SSDs instead of hard disks so read/write is magnitudes faster, plus we have separated out model data to a NAS now so there is less disk access in a single place with concurrent runs in progress than there used to be. 
On the current setup, I have not seen this corrupted tar issue occurring again, however this was a bigger issue for GC who had encountered this bug after very long (several hour) runs, so if this hasn't been specifically fixed, I believe there's still a case for adding better error handling (retrying) to this process to improve the user experience.

**Comment by mpinkerton-oasis** [comment]
@honlau what is the lates on this? Can you add a comment on the filesystem configuration that might have been the cause.

**Comment by honlau** [comment]
@mpinkerton-oasis we now believe that this was due to a configuration on the cifs mount (we mount a windows directory onto the linux servers) that was causing issues.
We've added a flag 'cache=none' to our cifs mount instruction on the /etc/fstab file in linux and have yet to see the error recurr.
This can be closed for now
