### ISSUE TITLE
Update schema file to handle sets of configuration parameters

### ISSUE THREAD

**Issue by JBADougBurns** [OasisLMF/OasisPlatform#345]
We have created a configuration parameter describing sets of configuration parameters, something which is implemented like this in the configuration files:
```
{
    "config_parameter_group": {
        "parameter_group_1": {
            "config_parameter_1": "A",
            "config_parameter_2": "B"
        },		
        "parameter_group_2": {
            "config_parameter_1": "A",
            "config_parameter_2": "B"
        }
    }
}
```
This allows for us to choose which set of configuration parameters we want at any given time.
For our model to be distributed via UI, the schema needs to be modified to be able to handle this.

**Comment by sambles** [comment]
> We see 3 cases that we would like to use:
> 1) The grouped config parameters would be added to the model_settings and a choice of which sets to use would be available from the UI. These would be ported to the analysis_settings.
> 2) The ability to overwrite an option for a particular group via the UI. Say patching/overwriting a set of defences.
> 3) The ability to create a new group from the UI. e.g. Client maps and defences in this region.
>
> In the end multiple ones would be ported to the analysis_settings if requested.

**Comment by sambles** [comment]
We do have an existing option `"parameter_groups"` that associates different types of parameters into a single group, but currently there is no option to set values. 

Would it make sense if we added a section to that called `"preselected_values"`  
where an entry is a dictionary listing the values for each parameter in the group? 


**Example**
```
      "parameter_groups":[                                                                                                                                     
        {                                                                                                                                                      
            "name": "boolean_group",
            "desc": "This is the presentation group for bools",
            "priority_id": 1,
            "presentation_order": ["peril_wind", "peril_surge"]
            "preselected_values: [
                "set_all_true": {
                    "peril_wind": True,
                    "peril_surge": True
                }, 
                "Set_all_false": {
                    "peril_wind": False,
                    "peril_surge": False
                }
            ]
        },  
        {   
            "name": "data_param_group",
            "desc": "This is the presentation group for other types",
            "priority_id": 2,
            "presentation_order": ["dictionary_option", "option_list", "option_str"]
            "preselected_values: [
                "option_1": {
                    "dictionary_option": {"A": "file_a", "B": "file_b", "C": "StringCol_1"},
                    "option_list": ["List_val_2", "List_val_5"],
                    "option_str": "String_value"
                },
                "option_2": {
                    "dictionary_option": {"A": "file_a", "C": "StringCol_2"},
                    "option_list": ["List_val_1", "List_val_4"],
                    "option_str": "someother_string_value"
                }
            ]
        }   
      ],  

```

**Comment by sambles** [comment]
Going for an open schema structure for the moment:
```
  ... 
 "multi_parameter_options":[ 
        {
            "name": "location_dependent_config_options",
            "desc": "Group description",
            "tooltip": "Detailed overview"
            "config": {  ...JSON DATA... }
        }, 
   ] 
```

Where `{ ...JSON DATA... }`  can be any json object, we can refine the spec later as needed
