### ISSUE TITLE
Lookup validation file content

### ISSUE THREAD

**Issue by sdaniel1609** [OasisLMF/OasisPlatform#349]
The structure of the lookup validation file in version 1.6.0 has change, which in turn is causing our processes to fail. 

Changes:
```
"total": {
        "modelled": {
            "tiv": 0,
            "number_of_locations": 0
        },
        "not-modelled": {
            "tiv": 0,
            "number_of_locations": 0
        },
        "portfolio": {
            "tiv": 0,
            "number_of_locations": 1
        }
    },
```

Should these changes be in the API spec file?

**Comment by sambles** [comment]
Hi @sdaniel1609  the API endpoint `/{version}/analyses/{id}/lookup_validation_file/`  is a file based response so doesn't have a schema attached to it.  But your right the structure should probably be documented somewhere. 

Do you have details on how the new "total" section caused a failure?  The rest of the file should remain unchanged, so i wouldn't expected additive changes to be an issue.

**Comment by sambles** [comment]
Old issue, closing
