### ISSUE TITLE
OED Field names

### ISSUE THREAD

**Issue by honlau** [OasisLMF/OasisPlatform#35]
I used the example info and scope files for testing reinsurance (files found here:
https://github.com/OasisLMF/ReinsuranceTestTool/tree/master/examples/acc_1_CAT_XL)
and I noted there were some cases where the header on the files differed from the input field name on the oed spec - please see CSV attached
[OED_differences.txt](https://github.com/OasisLMF/OasisPlatform/files/2558245/OED_differences.txt)

The files are quite old so I'm wondering if this was an earlier example or not.
Can you please check if the implementation in Oasis is expecting to find the names under "Oasis_name" or "OED_name" as I believe that they should be under the OED_name?

Thanks!

Hon

**Comment by sambles** [comment]
Matthew Jones [9:15 AM]
@pinkerton @joh Carter We are having some issues running reinsurance files through 0.396. Specifically: ReinsLayerNumber and TreatyShare seem to be mandatory fields (they shouldn't be) and, more importantly, in the reins_scope file it seems that blanks for PolNumber are not accepted - which makes filtering awkward if you have LocNumber (+AccNumber) filtering required where there are multiple policies in an account. Can you let me know which fields accept blanks and which do not, and whether there is a quick way to relax the mandatory requirement for some of the non-essential fields?

**Comment by mpinkerton-oasis** [comment]
Most of those columns aren't supported yet, so there is no name class. Perhaps are mis-labeled in some old examples.

File,OED_name,Oasis_name
INFO,ReinsPeril,ReinsPerilCode - unsupported so name not relevant
INFO,OccFranchiseDed,OccurenceFranchiseDed - unsupported so name not relevant
INFO,OccReverseFranchise,OccurenceReverseFranchise - unsupported so name not relevant
INFO,AggLimit,AggregateLimit - unsupported so name not relevant
INFO,AggAttachment,AggregateAttachmentPoint - unsupported so name not relevant
INFO,Reinstatement,ReinstatementNumber - unsupported so name not relevant
SCOPE,LocGroup,LocationGroup - Now correct
SCOPE,ReinsTag,ReinsuranceTag - unsupported so name not relevant
