### ISSUE TITLE
Release notes in github pages 

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisPlatform#354]
In release 1.7 the release notes are not being displayed correctly in the project docs

https://oasislmf.github.io

![release_notes_issue](https://user-images.githubusercontent.com/13663877/80036104-07b88100-84e9-11ea-8bdb-8b7a73d72d1e.png)

**Comment by sambles** [comment]
Updated it, the issue numbers `#`'s got picked up as markdown headings
