### ISSUE TITLE
Worker Monitor - Not updating DB on failure

### ISSUE THREAD

**Issue by lucaspanayiotou** [OasisLMF/OasisPlatform#381]
The worker monitor does not correctly flag runs as having failed in several scenarios. This causes a run status to remain in executing which in turn prevents any new analysis from progressing to the execution phase.

It should be noted that we are using kubernetes pods to run the workers, although this shouldnt make a difference in terms of monitoring.
Some scenarios we have observed are:
pod / container runs out of disk space, container crashes, status is not updated, pod restarts and sits idle.
pod / container runs out of memory, crashes, status is not updated, pod restarts and sits idle.

I don't recall other scenarios at this time but will append to this when they occur.

The expected behavior is that the worker monitor should update the status of the analysis to Failed.

**Comment by lucaspanayiotou** [comment]
I have reproduced the error and can confirm that nothing gets logged to /var/log/oasis/worker.log, nothing gets logged to stderror.err, and similarly the worker-monitor logs do not show anything.

I think docker / k8s could be losing the ability to write / monitor logs as the system reaches a critical level of resources.

FYI the process causing the failure is `leccalc`

While monitoring our container, I saw the memory utilization gradually rise to above 90%. I do not know exactly when the crash happened, but believe the system likely hit 100%, and then crashed as the worker demanded more memory.

**Comment by sambles** [comment]
**For memory:** 
The System OOM killer is killing the celery worker processes when trying to free up memory, if this happens there is nothing running to report back that a crash has happened.  

One option might be to use `ulimit -v` like the older memory guard setting, unfortunately that works on a per-process limit so its not ideal.  

Another option might be to try and protect the celery processes from being killed. 
https://www.oracle.com/technical-resources/articles/it-infrastructure/dev-oom-killer.html

**Comment by ndaqjn** [comment]
Can't you detect through celery that the worker is gone and the status is still executing?

**Comment by mpinkerton-oasis** [comment]
We should be able to use celery heartbeats to fail or retry the task. In terms of the worker, we should implement a health check that will allow you to recycle the worker. Is a particular interface that the health check should conform to?

**Comment by sambles** [comment]
Fix Merged in with PR #393
