### ISSUE TITLE
Error While running  DOcker file  for API Server

### ISSUE THREAD

**Issue by nitheeshunni** [OasisLMF/OasisPlatform#399]
When the  below command reaches  
Step 45/49 : RUN OASIS_API_SECRET_KEY=supersecret python manage.py collectstatic --noinput

Error is  thrown 
file "/usr/local/lib/python3.6/site-packages/django_filters/utils.py", line 10, in <module>
452     from django.db.models.fields import FieldDoesNotExist
453 ImportError: cannot import name 'FieldDoesNotExist'
454 The command '/bin/sh -c OASIS_API_SECRET_KEY=supersecret python manage.py collectstatic --noinput' returned a non-zero code: 1
457 ERROR: Job failed: exit code 1

**Comment by sambles** [comment]
Hello @nitheeshunni  Thanks for the Issue! 

Its from changes in a recent Django release:
https://docs.djangoproject.com/en/dev/releases/3.1/
```
The compatibility import of django.core.exceptions.FieldDoesNotExist in django.db.models.fields is removed.
```
I've added a fix (https://github.com/OasisLMF/OasisPlatform/commit/76311e5b260a39615fd3df0e0bf4a6f4b2571c80) by pinning Django to `3.0.8`, if you git pull that it should build now. We'll need to make some changes for compatibility with `Django==3.1`

**Comment by nitheeshunni** [comment]
i have made the changes to the  django version  in the requirements file and  i have tried to build again ,throws  different  error

ERROR: Could not find a version that satisfies the requirement djangowebtest==1.9.7 (from -r ./requirements.txt (line 39)) (from versions: 0.1.1)

**Comment by sambles** [comment]
Whats the command you're running?  There are a few requirement files:
```
requirements.txt  <--  Development files (like djangowebtest for unittesting) 
requirements-server.txt <-- server image python requirements
requirements-worker.txt <-- worker image python requirements
```

If you are docker building it should only need the server/worker requirements

**Comment by nitheeshunni** [comment]
Thank you so much @sambles  
Now it is working Perfect
