### ISSUE TITLE
OED required fields to re-assess

### ISSUE THREAD

**Issue by honlau** [OasisLMF/OasisPlatform#40]
There is a difference between the required fields for INFO and SCOPE files specified in the OED spec and that implemented in Oasis 396.
The requirements need to be re-assessed between Oasis and Simplitium to determine which fields can remain as required fields and which can be derived/dummied instead.

Attachment highlights differences between implementation and OED spec.
[Info_Scope_RequiredFields_mj_comments.xlsx](https://github.com/OasisLMF/OasisPlatform/files/2595892/Info_Scope_RequiredFields_mj_comments.xlsx)

**Comment by mpinkerton-oasis** [comment]
@honlau can this be closed?
