### ISSUE TITLE
Let environment variables override settings in conf.ini?

### ISSUE THREAD

**Issue by johanxnilsson** [OasisLMF/OasisPlatform#408]
There is currently no way to override settings in conf.ini for the worker. Environment variables seems to be the fallback option if the value isn't found in conf.ini. To change a value you need to mount a new conf.ini file.

Would it make more sense to change the order and pick the environment variable as first choice and use conf.ini as fallback? By doing so we can keep the workers default settings but override things like storage with environment variables if needed.

**Comment by sambles** [comment]
**Notes:** Inside a docker image the environment vars should override config files, but not when running directly in the MDK.

**Comment by johanxnilsson** [comment]
This works great with the OASIS_ prefix for these environment variables. You can close this ticket.
