### ISSUE TITLE
S3 storage type makes oasis return unzipped .tar.gz files

### ISSUE THREAD

**Issue by jxn0** [OasisLMF/OasisPlatform#412]
If you change the storage type to S3 and queries the api for either input, log or output files (maybe other types as well?) you will get a file with the .tar.gz suffix but it won't be zipped. The files stored on S3 is however zipped and named .tar.gz.

**Comment by sambles** [comment]
**Note:** 
Might be connected to https://github.com/aws/aws-cli/issues/5228 
The file looks to be compressed when uploaded to S3

**Comment by sambles** [comment]
looked like it was an issue in the boto3 lib, couldn't find a workaround, closing for the moment
