### ISSUE TITLE
Give the API user the possibilty to manage files outside of oasis

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/OasisPlatform#419]
In a managed deployment, using oasis to upload and download files is one additional level of indirection that is not required. 

**Exposure files**
A preferred solution is that the deployed system manages the files outside of oasis, but have the possibility to pass in references to the files and link them to the portfolio. 

**Output files**
This is also true for downloading results or intermediate files from oasis. The api should return the filename and the system can then download the files directly from the source.

**Comment by sambles** [comment]
Pull request #425
