### ISSUE TITLE
No sidx = -1 OEP or AEP curves in Wheatsheaf output

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/OasisPlatform#43]
There seem to be no numerically-integrated-mean (sidx=-1) OEP or AEP curves in the Wheatsheaf output using Oasis 0.396 (ModEx 3.0.0.). Tested using the Nationwide portfolio and the ARA Hurloss model.

**Comment by jones-matt** [comment]
I understand this was intended to avoid having different types of curve in the Wheatsheaf output - which I think makes sense. However is there another way for clients to access the sid=-1 OEP/AEP curve. Client feedback (from GC, Canopius and Ascot) is that it would be useful to keep this curve accessible somehow.

**Comment by mpinkerton-oasis** [comment]
@johcarter any thoughts on this?

**Comment by johcarter** [comment]
Running the single EP curve with 0 samples will produce the numerically integrated EP curve
