### ISSUE TITLE
Add reporting output dependency by event_set to model_settings.json

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/OasisPlatform#438]
It should be possible to restrict the outputs available (perspectives (gu, il, ri) and metrics (8 ep curves, aal, plt, elt, samples)) given specific event set selections. For example, time based metrics such as EP and AAL are not relevant for cat response event sets, and may not be appropriate within some models for historical event sets. Suggest that the model_settings.json schema is enhanced to allow this dependency (in a similar way to the event_set / occurrence_id dependency which is already part of the schema).

**Comment by sambles** [comment]
See the Pull Request notes for details: https://github.com/OasisLMF/OasisLMF/pull/694

added as `"valid_perspectives": [ .. str values .. ]` 
and `"valid_metrics": [ .. str values .. ]`
```
 "event_set":{
         "name":"Event Set",
         "default":"P",
         "desc": "Lists of event sets",
         "options":[
            {   
               "id":"P",
               "desc":"Probabilistic",
               "valid_occurrence_ids":["1"],
               "valid_perspectives": ["gul", "il"],
               "valid_metrics": ["plt", "elt"]
            }
        ]
```
