### ISSUE TITLE
Change log level to hide sensitive http headers

### ISSUE THREAD

**Issue by johanxnilsson** [OasisLMF/OasisPlatform#454]
For security reasons we need to hide log entries containing the `X-Amz-Security-Token` HTTP header in oasis server, like this one:

`DEBUG 2021-01-12 15:49:33,663 endpoint 45 140343329900288 Sending http request: <AWSPreparedRequest stream_output=True, method=GET, url=https://truncated.json, headers={'User-Agent': b'Boto3/1.11.15 Python/3.6.12 Linux/4.14.198-152.320.amzn2.x86_64 Botocore/1.14.15 Resource', 'X-Amz-Date': b'20210112T154933Z', 'X-Amz-Security-Token': b'IQoJb3JpZ2luX2Vj..truncated..==', 'X-Amz-Content-SHA256': b'e3b0c442b855', 'Authorization': b'AWS4-SHA256 Credential=ASIAUOA/20210112/eu-west-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=b5fde18bf0315efe2840167'}>`

As a quick fix we can do this by setting the log level to INFO but this will turn off logging completely since all log entries use the DEBUG level at the moment. Could we change or split the log entries containing the `X-Amz-Security-Token` and make it log on level TRACE (or similar below DEBUG)? This would hide sensitive information but still be possible to display it if needed.

**Comment by sambles** [comment]
https://github.com/boto/boto3/issues/521 -- edit the boto3 loggers to hide sensitive info
