### ISSUE TITLE
Reinsurance: Remove requirement for certain fields in reins_info file

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/OasisPlatform#46]
Currently the following fields are all required to be present in the reins_info and reins_scope input files:

**reins_info**
ReinsNumber,ReinsLayerNumber,CededPercent,RiskLimit,RiskAttachment,OccLimit,OccAttachment,InuringPriority,ReinsType,PlacedPercent,TreatyShare
**ri_scope**
ReinsNumber,PortNumber,AccNumber,PolNumber,LocNumber,RiskLevel,CededPercent

We need to think more carefully about which fields should be required and which should not as there is underlying business logic relating to differnt types of RI. However suggest for now remove a requirement for the following fields:

**reins_info**: ReinsLayerNumber, TreatyShare

**Comment by mpinkerton-oasis** [comment]
In 397 required fields follow OED spec
