### ISSUE TITLE
Worker - Stuck idle on some bash errors

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#464]
Bash script Trap function is missing the `EXIT` sig, 

https://github.com/OasisLMF/OasisLMF/blob/master/oasislmf/execution/bash.py#L80

**Comment by ndaqjn** [comment]
Will you do a 1.13.x and 1.14x release with this fix as well? It's a big step to go to 1.15

**Comment by sambles** [comment]
I can patch those if needed, whats the main blocker for moving to `1.15`, the switch to fmpy?

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisLMF/pull/787
