### ISSUE TITLE
Reinsurance: Any values in Limit or Attachment fields in reins_info file should be treated as zero if entered as blank

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/OasisPlatform#47]
There is variation in the behaviour of the reinsurance module if limit or attachment fields in the reins)info file are entered as blanks versus entered as zero. Currently this applies to OccLimit, OccAttachment, RiskLimit, RiskAttachment. If blanks are entered for these fields they should be treated the same as zeros.

(NB: for limit fields this means that the limit in the Python code should be treated as unlimited - not zero)

**Comment by mpinkerton-oasis** [comment]
This is now treated in the same way as 0s. See test cases:
    'simple_CAT_XL',
    'simple_CAT_XL_0_occ_limit_treat_as_unlimited',
    'simple_CAT_XL_empty_occ_limit_treat_as_unlimited'

To merge from branch feature/full_reinsuarnce_filtering

**Comment by mpinkerton-oasis** [comment]
Fixed in 0.397
