### ISSUE TITLE
Reinsurance: trailing blank rows in reins_info or reins_scope csv files causes fail

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/OasisPlatform#48]
If trailing blank rows (ie rows that are just a series of commas) are present in the reins_info or reins_scope csv input files this causes a fail. Excel often creates empty rows of data when generating csv files so this will be a common issue.

**Comment by jones-matt** [comment]
[OED_NationwideDF_reins_info_ss.zip](https://github.com/OasisLMF/OasisPlatform/files/2638968/OED_NationwideDF_reins_info_ss.zip)

**Comment by mpinkerton-oasis** [comment]
That seems like the correct behavior in the API as this input data is invalid. Perhaps you could validate this or catch the invalid data in the UI if you want to explicitly support Excel issues? I believe that there is some data validation performed in Modex?

**Comment by jones-matt** [comment]
OK, but this is a regression from the way acc / loc files currently work (OED or RMS acc/loc files with trailing blank rows currently run) which is why the behaviour is unexpected. We can deal with it UI side if you are not going to catch this behavior API side, so fine to close.

**Comment by mpinkerton-oasis** [comment]
Okay. I think that is a function of doing minimal up-front validation on the acc/loc files, so this would have ran by default.
