### ISSUE TITLE
How to limit user permissions to only view certain models on the Platform?

### ISSUE THREAD

**Issue by macabuag** [OasisLMF/OasisPlatform#484]
-	Via the Django administration dashboard, I don’t seem to be able to restrict specific models/analyses/portfolios for different users. I.e. I cannot see how you would give different Clients access to different models. 
-	Is this functionality implemented?

![image](https://user-images.githubusercontent.com/31392092/114869000-6bb91100-9dee-11eb-9bc4-1e15df6b3d5c.png)

**Comment by sambles** [comment]
Hello @macabuag  this functionality hasn't been implemented yet. 

However, its planned in the next architectural update for the OasisPlatform, where functionally will be added for Performance, Reliability & security. 

The goal is to create a more fully featured `Enterprise Platform` reference, with an approximate time frame of: 
## (first 6 months of work)
* Kubernetes Integration  
* Horizontal Autoscaling
* security and user-management
.. more general architectural updates.. 

## (next 6 months of work)
* Azure deployment  and Integration with cloud services

**Comment by sambles** [comment]
This has been added to the newer platform [platform-2.0](https://github.com/OasisLMF/OasisPlatform/tree/platform-2.0)

Documentation:  [kubernetes/charts#keycloak](https://github.com/OasisLMF/OasisPlatform/tree/platform-2.0/kubernetes/charts#keycloak)
