### ISSUE TITLE
Reinsurance: LocNumber scope field requires PolNumber and AccNumber also rather than just AccNumber

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/OasisPlatform#49]
In the reins_scope file it should be possible to define a location scope using LocNumber and AccNumber. However, currently if PolNumber is not also entered the run fails. Need to modify Python code to not require PolNumber.
[test 12.zip](https://github.com/OasisLMF/OasisPlatform/files/2639000/test.12.zip)

**Comment by mpinkerton-oasis** [comment]
Ready to merge from feature/full_reinsurance_filtering

**Comment by mpinkerton-oasis** [comment]
Fixed in release 0.397
