### ISSUE TITLE
Reinsurance: surplus share run continues indefinitely

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/OasisPlatform#50]
The attached files satisfy the criteria that Mark P laid out for a successful reinsurance run, however the analysis seems to carry on indefinitely. I set off the standard Nationwide run on Friday and still running on Monday morning (ModEx UAT Support2). 
[test 17.zip](https://github.com/OasisLMF/OasisPlatform/files/2639007/test.17.zip)

**Comment by mpinkerton-oasis** [comment]
I'm pretty sure this was fixed and was an issue in the Flamingo server. @jones-matt, can you re-open if not.
