### ISSUE TITLE
Celery connection issue blocking tasks from completing 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#516]
## Issue Description
Network interruptions between celery and the worker/worker-monitor containers causes an error when reporting a task's status back to the API. 

>**Johan Nilsson:** We just had a worker hang and we think it might had something to do with the celery connection, but I just realized the run wasn't started when it happened.

> **Johan Nilsson:** This is the worker log, it runs the input gen successfully, and then it received the task run_analysis but while executing the connection to celery is lost for a few seconds until it reconnected successfully. However 20 seconds later the same task is received again **run_analysis[6a0abc1e-d74d-4e96-bfe0-4f17c585d75b]** which seems to run for a few hours until it is terminated.

> **Jonas Nordin:** I think this was related to either the worker or worker monitor temporarily loosing network connectivity.When that happened the analysis didn't get marked as completed. I think if you just bring down the network connection from the worker to celery you should be able to emulate it

## Version / Environment information
* Known to occur on LTS versions `1.15.8` and `1.13.0`

## Example data / logs
[worker_log.txt](https://github.com/OasisLMF/OasisPlatform/files/6807315/worker_log.txt)

**Comment by benhayes21** [comment]
closing until it happens again
