### ISSUE TITLE
Mechanism to set default Alloc rule 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#52]
Add an option for a worker to default to either Alloc Rule 1 or 2

**Comment by sambles** [comment]
need to switch between:
`ALLOCATE_TO_ITEMS_BY_GUL_ALLOC_ID` rule 1
`ALLOCATE_TO_ITEMS_BY_PREVIOUS_LEVEL_ALLOC_ID`  rule 2

in:
https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/model_execution/bash.py

**Comment by mpinkerton-oasis** [comment]
@sambles any update on this?

**Comment by sambles** [comment]
Added, for worker containers use
```
KTOOLS_ALLOC_RULE_GUL = {0/1}
KTOOLS_ALLOC_RULE_IL = {0/1/2}
```

for MDK use:
```
--ktools-alloc-rule-gul {0/1}
--ktools-alloc-rule-il {0/1/2}
```

```
