### ISSUE TITLE
Add tool to enable fm loss testing for fm files generated by MDK

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisPlatform#54]

**Comment by sr-murthy** [comment]
@johcarter If this issue requires adding to existing MDK functionality then it should also be an issue in the MDK repository.

**Comment by johcarter** [comment]
I can't see that repo. what is its official name?

**Comment by sr-murthy** [comment]
The MDK repository name is also OasisLMF. The issues page is here

https://github.com/OasisLMF/OasisLMF/issues

**Comment by johcarter** [comment]
moved to OasisLMF repo
