### ISSUE TITLE
Policy Level AAL incomplete

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/OasisPlatform#56]
Running the standard ARA Nationwide Portfolio on ModEx UAT Support 2 with Policy Level AAL produces no output for the Layer2 policy:

![image](https://user-images.githubusercontent.com/42215881/50079057-7e03ef80-01e0-11e9-8009-76f811baa823.png)

ModEx 3.0.7
Oasis 0.397.1

**Comment by mpinkerton-oasis** [comment]
@jones-matt can this be closed?

**Comment by jones-matt** [comment]
Yes, fine to close Matk. Thanks.
