### ISSUE TITLE
Upload location file server error

### ISSUE THREAD

**Issue by jacoblann** [OasisLMF/OasisPlatform#566]
I followed the instructions to set up the development environment on my own PC, after having the server running, I found there's this Server Error (500) while I try to upload a location file, can you please let me know how to fix this? Thanks!
![Oasis_upload_file](https://user-images.githubusercontent.com/36351236/144008144-0f25926e-2d69-414e-ac81-ba463c6bbf31.png)
![Oasis_upload_file_error](https://user-images.githubusercontent.com/36351236/144008148-d04275fa-7912-4735-ac43-95b35b49a7bf.png)

**Comment by sambles** [comment]
Hi @jacoblann can i get more information on your environment and the Oasis platform version. 
I've tried to reproduce what your seeing using the versions `1.22.0` and `1.15.21-lts`. Both seem to work when running the example install script https://github.com/OasisLMF/OasisEvaluation and all seems fine. 

- How are you running the server, is it via docker containers or directly in python  (using `./manage.py runserver`)?
- OS version 
- Oasis version
- (If running externally via python) the python version  


![platform_check_1](https://user-images.githubusercontent.com/9889973/144048829-4d6aed79-d7df-45e4-a451-43448a9cf13d.png)

![platform_check_2](https://user-images.githubusercontent.com/9889973/144048840-9a58d233-71a7-41e8-ac5f-8ca0c412fdda.png)

**Comment by jacoblann** [comment]
Hi @sambles, thanks a lot for your timely reply and sorry for not making clear of my issue. I have no problem adding a Portfolio, which I can find in the db.sqlite3 file after added.

Only when it comes to uploading a file, not necessarily a location file, there's this Server Error 500. I'm thinking if I was missing any steps.

- I am running the server directly in Python, version 3.9.7, with the command "python manage. py runserver".
- OS version: CentOS 7.
- Oasis version: I cloned the latest code from [OasisPlatform](https://github.com/OasisLMF/OasisPlatform), I think it should be 1.22.0.

Thanks again!

**Comment by sambles** [comment]
Okey that makes sense, before running the server via python you first need to edit the file storage location in this file

https://github.com/OasisLMF/OasisPlatform/blob/develop/conf.ini#L10
```
MEDIA_ROOT = /shared-fs/
```

The server is trying to store uploaded files in a root folder which it wont have access to, so it throws a server error. 
It should work if you edit that value to `./shared-fs/`

**Comment by jacoblann** [comment]
Yes that fixed it, thanks!
