### ISSUE TITLE
Cannot Generate Inputs after platform restart

### ISSUE THREAD

**Issue by macabuag** [OasisLMF/OasisPlatform#605]
## Issue Description
When taking containers down and then up again, analysis hangs at the input generation stage (status does not progress past “inputs generation queued”, screenshot below).
1. Scenario 1 (works ok): deploy model, create portfolio & run via UI
2. Scenario 2 (works ok): create new portfolio & run via UI (on same model)
3. **_Scenario 3 (does not work): take containers down & up again, then repeat Scenario 2_** (create new portfolio & run on existing model, without deploying a new one)
    - Also can’t regenerate inputs, even on previously successful analyses (i.e. pressing "Generate Inputs" on an analyses with status "run completed", will again hang at "inputs generation queued").
    - Note that previous analyses are visible, and previous results can be viewed (so volumes are persisting, as expected)
4. Scenario 4 (works ok): take containers down & up again, then repeat Scenario 1 (deploy new model, create new portfolio & run)

This essentially means we cannot run any models after platform restart. **_Any idea how to resolve?_**

## Steps to Reproduce
To reproduce **_scenario 3_** above:
1.	Run any model/portfolio as normal
2.	Then ‘docker-compose down’ & ‘docker-compose up’
3.	Run same model/portfolio (should hang at input generation stage)
4.	Also try regenerating input on previously successful model/portfolio run (should hang at input generation stage)

## Version / Environment information
Tested on WSL (Windows 10 / Ubuntu 20.04.2 LTS) and native Ubuntu (both locally and on AWS EC2 instance)

## Example data / logs
![Screenshot of Problem](https://user-images.githubusercontent.com/31392092/155712483-b9db259d-fe4b-45f9-a72b-d47cc463a1e0.png)

**Comment by sambles** [comment]
Hi @macabuag

status `inputs generation queued`​ points to a problem with the worker starting or its connecting to celery. 

Can you share the following to help debug?
-     Worker container logs (after running scenario 3)
-     The docker compose file(s)

**Comment by sambles** [comment]
resolved over debugging call - closing
