### ISSUE TITLE
GitHub action to deploy model? 🏷️ Question

### ISSUE THREAD

**Issue by dholdaway** [OasisLMF/OasisPlatform#607]
Hello,

Just wondering if there was a GitHub Action to deploy models?

**Comment by sambles** [comment]
An deploying models to the updated platform  was added via Azure Devops pipelines, see  [OasisAzureDeployment - DevOps pipeline](https://github.com/OasisLMF/OasisAzureDeployment#22-prepare-devops-pipeline)

Github actions should work as a drop-in replacement using the same scripts, but its not something we've tried yet.
