### ISSUE TITLE
API - Http Responses with a 204 status should not have a content-length header

### ISSUE THREAD

**Issue by jonathanbethel** [OasisLMF/OasisPlatform#67]
While using DEL /portoflios/{id} API call, the http status returned is 204 (NO CONTENT), with no body. 

However a header of Content-Length: 0 is set, which is non HTTP compliant. There should just be no Content-Length header present.

Although it seems like a very minor issue, it will cause a lot of http client libraries to throw an error when a the response is received by the client, due to it being non-compliant.

According to RFC 7230 [1]: 
[1] https://tools.ietf.org/html/rfc7230 

   A server MUST NOT send a Transfer-Encoding header field in any 
   response with a status code of 1xx (Informational) or 204 (No 
   Content). A server MUST NOT send a Transfer-Encoding header field in 
   any 2xx (Successful) response to a CONNECT request (Section 4.3.6 of 
   [RFC7231]). 

   A server MUST NOT send a Content-Length header field in any response 
   with a status code of 1xx (Informational) or 204 (No Content). A 
   server MUST NOT send a Content-Length header field in any 2xx 
   (Successful) response to a CONNECT request (Section 4.3.6 of 
   [RFC7231]).

**Comment by sambles** [comment]
I think this is a Django REST framework behavior, sending any DELETE request with a status_code return of  `204`  also has `Content-Length: 0` in the header. I'm not sure why that would be if its non-compliant.
