### ISSUE TITLE
Fix High log volume from numba debug logger  

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#678]
## Issue Description

> found when testing 1.26.2 worker in https://github.com/OasisLMF/OasisUI/pull/289

The loss output log file generated by the 1.26.x workers create a large amount of text. seen examples of logs around 44Mb~ (350k lines, mostly of numba debug logs)

**Comment by sstruzik** [comment]
fix in https://github.com/OasisLMF/OasisLMF/pull/1107
