### ISSUE TITLE
API - token expiry times are unclear

### ISSUE THREAD

**Issue by jonathanbethel** [OasisLMF/OasisPlatform#68]
The response to /access-token/ contains both the refresh_token and access_token values.

However it only contains one expires_in value, which is for the refresh token (86400). 

In order to obtain the access token expires_in value (3600), an call to /refresh_token/ needs to be made. The access-token API should contain both.

Being that these tokens are JSON web tokens, you might see this as redundant. It would be helpful for this to be documented somewhere in the Django API though as other clients of the API might not be familiar with JSON Web tokens. Having these both stated explicitly in the /access_token/ response would be the most clear solution I think.

**Comment by sambles** [comment]
The relevant section in the code is here:
https://github.com/OasisLMF/OasisPlatform/blob/beta-release/1.0.0/src/server/oasisapi/auth/serializers.py#L10-L45

Looks like the `expires_in` field is set based on the endpoint call
