### ISSUE TITLE
API - Add ability to re-link analysis to an existing exposure file

### ISSUE THREAD

**Issue by jonathanbethel** [OasisLMF/OasisPlatform#69]
In the previous version of oasis we deployed there was functionality that enabled relinking exposure files, which had already been uploaded to the system, to a new portfolio. 

If a user wants to re-use a file now they have to re-upload the file, which could be quite onerous for large files. 

I understand that a user could just use the old portfolio that the files were originally linked to, but there are a number of cases where this may not be viable or possible. 

For instance, the original portfolio may have been deleted, or a user may want to have their own separate portfolio with analyses separate from another users analyses.

How much work would this require? It is something that we would be keen to have available for Modex.

**Comment by sambles** [comment]
It would be possible as the uploaded files are kept in the shared file store directory but we would need a way to present whats in the system, possibly via a `/v1/files/{id}` endpoint.

And also a way to connect an existing file id when issuing a POST  `/v1/portfolios/{id}/ ...`

**Comment by sambles** [comment]
Note: its better to run `PATCH` on `/v1/portfolios/{id}` rather than POST
