### ISSUE TITLE
Installation error (Mac)

### ISSUE THREAD

**Issue by calvinccs** [OasisLMF/OasisPlatform#701]
Cannot start service api_evaluation_notebook

## Issue Description
Try to install in my work laptop, which I don't have root access and it is how the error was caused:

------
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Starting api_evaluation_notebook_api_evaluation_notebook_1 ... error

ERROR: for api_evaluation_notebook_api_evaluation_notebook_1  Cannot start service api_evaluation_notebook: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/host_mnt/Users/XXXXX/DataBox/OasisEvaluation/OasisPiWind/analysis_settings.json" to rootfs at "/home/run/data/analysis_settings.json": open /var/lib/docker/overlay2/54ec592e786f313d3de64597c3e00fb142d5a4f8e47e44b137b0c63819b93070/merged/home/run/data/analysis_settings.json: operation not permitted: unknown

ERROR: for api_evaluation_notebook  Cannot start service api_evaluation_notebook: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/host_mnt/Users/XXXXX/DataBox/OasisEvaluation/OasisPiWind/analysis_settings.json" to rootfs at "/home/run/data/analysis_settings.json": open /var/lib/docker/overlay2/54ec592e786f313d3de64597c3e00fb142d5a4f8e47e44b137b0c63819b93070/merged/home/run/data/analysis_settings.json: operation not permitted: unknown
-----

## Version / Environment information
macOS Big Sur

**Comment by sambles** [comment]
Hello @calvinccs The `api_evaluation_notebook` isn't really needed to get the demo up and running, its intended to be a demo for running the Python API client (installed along with the oasislmf package) 

Try deleting or commenting out the following lines of the install script. (from line 96 and down) 
https://github.com/OasisLMF/OasisEvaluation/blob/772077ad687de03d894375abe15c2ffc24ba1303/install.sh#L96-L109

**Comment by calvinccs** [comment]
Got it, thanks!

**Comment by benhayes21** [comment]
Closing issue, assume fixed
