### ISSUE TITLE
API is down. Try again later

### ISSUE THREAD

**Issue by dw20587066d** [OasisLMF/OasisPlatform#704]
I am not able to login the the OasisUI Interface. After following the steps, I found that API Swagger UI and API Admin Panel run smooth, but I cannot open the OasisUI Interface. And "API is down. Try again later." was shown on the page. May I know how to solve this problem. Thanks.

**Comment by sambles** [comment]
Hi @dw20587066d  was the platform install from [OasisEvaluation](https://github.com/OasisLMF/OasisEvaluation)

We've updated the install script to simply the UI networking which should solve the problem. 
https://github.com/OasisLMF/OasisEvaluation/pull/33

**Comment by benhayes21** [comment]
Closing - assume fixed
