### ISSUE TITLE
FM Oasis file generation performance

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisPlatform#76]
Improve the performance of the Oasis FM file generation process. Minimum target is 1MN locations processed in under 10mins on AWS T2.medium instance or comparable.

**Comment by sr-murthy** [comment]
Further optimisation of the FM component (and also GUL phase) will be done as part of the next release.

**Comment by sr-murthy** [comment]
@mpinkerton-oasis There are many variables which affect runtime - we have to also include in the 1MN portfolio benchmark you've stated that it relates to a single peril and coverage type model. As when you have multiple perils and coverage types, say P perils and C coverage types, you end up getting an expanded set of data, N x P x C, where N is the no. of locations, and clearly to generate N x P x C GUL input items say, will take proportionally longer than to generate N input items.

**Comment by mpinkerton-oasis** [comment]
We will create an appropriate target portfolio, but would assume single peril and 3 coverages to start.

**Comment by mpinkerton-oasis** [comment]
Also, please track status in release board: https://github.com/orgs/OasisLMF/projects/9

**Comment by sr-murthy** [comment]
I seem to remember that the original benchmark mentioned with regards to the single-peril and coverage type version of PiWind was 1Mn locations in under 10 minutes. This is feasible, and implies a 10K runtime of ~ 6 seconds. With three coverage types, you won't be able to run 1MN locations in under 10 minutes, as the 10K runtime would be ~18 seconds.

**Comment by sr-murthy** [comment]
https://github.com/OasisLMF/OasisLMF/tree/feature/optimise-fm
