### ISSUE TITLE
Oasis Evaluation environment - error when trying to login

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisPlatform#87]
I've installed the Oasis Evaluation environment by running the `install.sh` script on Scientific Linux 7.5, Docker v1.18.0. I am able to access the web UI via `http://computer-name:8080/app/BFE_RShiny`, but when I try to log in with the user/pass the Oasis Evaluation repo tells me to use, the page stops responding and greys out.

The output of `docker ps -a` is as follows:
```CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                         PORTS                                                                                        NAMES
bd647b89c50b        coreoasis/oasisui_app:1.0.0-rc1     "R -e flamingo::runF…"   30 minutes ago      Up 30 minutes                  3838/tcp                                                                                     vigilant_rosalind
62923e5c6d83        coreoasis/oasisui_proxy:1.0.0-rc1   "/bin/sh -c ./startu…"   About an hour ago   Up About an hour               0.0.0.0:8080->8080/tcp                                                                       oasisui_proxy
ee636b907cb8        coreoasis/api_server:1.0.1          "startup wait-for-se…"   About an hour ago   Up About an hour               8000/tcp                                                                                     oasisplatform_worker-monitor_1
c77feca89efc        coreoasis/api_server:1.0.1          "startup ./uwsgi/run…"   About an hour ago   Up About an hour               0.0.0.0:8000->8000/tcp                                                                       oasisplatform_server_1
d1107c9c53ff        coreoasis/model_worker:1.0.1        "/bin/sh -c ./startu…"   About an hour ago   Up About an hour                                                                                                            oasisplatform_worker_1
6c4fab02927b        iserko/docker-celery-flower         "flower --port=5555 …"   About an hour ago   Up About an hour               0.0.0.0:5555->5555/tcp                                                                       oasisplatform_flower_1
8b09596a584f        mysql                               "docker-entrypoint.s…"   About an hour ago   Up About an hour               3306/tcp, 33060/tcp                                                                          oasisplatform_server-db_1
6b3767d436b4        rabbitmq:3-management               "docker-entrypoint.s…"   About an hour ago   Up About an hour               4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   oasisplatform_rabbit_1
84c5dc8dd82f        mysql                               "docker-entrypoint.s…"   About an hour ago   Up About an hour               3306/tcp, 33060/tcp                                                                          oasisplatform_celery-db_1
```

Running `docker logs vigilant_rosalind -f` (i.e. the logs of the oasisui_app image), the following error is reported when I try to login:
```
Warning: Error in curl::curl_fetch_memory: Failed to connect to 172.20.0.1 port 8000: No route to host
  79: curl::curl_fetch_memory
  78: request_fetch.write_memory
  76: request_perform
  75: POST
  74: api_access_token
  73: observeEventHandler
   2: runApp
   1: flamingo::runFlamingo
```

None of the other logs I've inspected contain anything obviously useful.

**Comment by DanielFEvans** [comment]
Looking in a bit more detail with `docker inspect`, there doesn't seem to be any container with the IP address 172.20.0.1. The `oasisui_app` is on 172.20.0.3, and `oasisui_proxy` on 172.20.0.2; the rest are all 172.19.0.x.

**Comment by sambles** [comment]
Hi DanielFEvans, 

It looks like the *oasisui_app* container can't find the oasis_api container.  Can you confirm:
1. That you can access and login on the API directly at http://localhost:8000 
2. The Gateway address of the *oasisui_proxy* container `docker inspect oasisui_proxy`, it should be under the networks section. 

The Gateway address should match what you are seeing in the docker logs i.e. `172.20.0.1`
That address is mapping back the the host outside of docker which the app is using to make the API calls. It might be failing because the two don't match up some how. 

You can explicitly set the IP address by using the environment variable `API_IP` in
https://github.com/OasisLMF/OasisUI/blob/develop/docker-compose.yml#L10

If left blank the container runs the following line at startup to set the Gateway IP automatically:
https://github.com/OasisLMF/OasisUI/blob/develop/shinyproxy/startup.sh#L8

**Comment by DanielFEvans** [comment]
Hi Sam,

1. Yes, I can access the API directly on port 8000.
2. The Gateway address listed is: `"Gateway": "172.20.0.1"`

**Comment by DanielFEvans** [comment]
Aha, solved this one - it was a local firewall issue, which was refusing the connections to/from the Docker containers, even though I could access them manually.

This was what tipped me off: https://forums.docker.com/t/no-route-to-host-network-request-from-container-to-host-ip-port-published-from-other-container/39063
