### ISSUE TITLE
Keys chunks can silently fail when hitting memory pressure

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#885]
## Issue Description
If a keys chunk crashes with an OOM sigkill, the collect keys process will continue and the error is not detected.

**Comment by sambles** [comment]
> Also: `investigate slowness of collect keys and write input files functions when running JBA models in EO`

**Comment by sambles** [comment]
* Add check keys_df + keys_error_df, should match up with unique `loc_id` in `location_df` 
* Add better error detection within each keys chunk sub-task

**Comment by benhayes21** [comment]
closing - fixed
