### ISSUE TITLE
Add post analysis hook to platform 2 workflow 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#910]
## Issue Description
Feature from https://github.com/OasisLMF/OasisLMF/pull/1371 added a new post analysis hook. 

This needs to called in the worker, either after or during the `generate_losses_output` step 
https://github.com/OasisLMF/OasisPlatform/blob/7c7aee6822d3be5e45a98298cffc48fee5cbc58a/src/model_execution_worker/distributed_tasks.py#L1040-L1060

**Comment by carlfischerjba** [comment]
@sambles thanks for creating this. Am I right in thinking that platform 1 will already include the post analysis hook without any changes to OasisPlatform, due to it being included in an existing loss generation function?

**Comment by sambles** [comment]
yes exactly, it should work in platform 1 without the need to edit the worker code
