### ISSUE TITLE
ODS Tools link in release notes points to OasisLMF repo

### ISSUE THREAD

**Issue by fl-ndaq** [OasisLMF/OasisPlatform#920]
**IMPORTANT: Please apply the relevant labels, for example if this issue is needed as a backported fix add the label `LTS fix` (Long term support fix)

## Issue Description

ODS Tools link in release notes points to OasisLMF repo

## Steps to Reproduce (Bugs only)

1. go to https://github.com/OasisLMF/OasisPlatform/releases
2. pick any release and click on the ods-tools version link under Components, e.g. 1.28.3 > [ods-tools 3.1.2](https://github.com/OasisLMF/OasisLMF/releases/tag/3.1.2)

**Comment by fl-ndaq** [comment]
@sambles this is closed two weeks ago but was not pulled into any version, 1.28.4 still has the same issue

**Comment by sambles** [comment]
I had to manually recreate the changelog / release notes due to this issue, https://github.com/OasisLMF/OasisPlatform/issues/927 

The branch i used must have not had the fix (Sorry my mistake)
